AWSTemplateFormatVersion: 2010-09-09
Description: Web Content Infrastructure

Parameters:
  Stage:
    Description: Environment stage
    Type: String
    Default: dev

Resources:
  StaticWebsite:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

Outputs:
  WebsiteURL:
    Value: !GetAtt StaticWebsite.WebsiteURL
  WebsiteArn:
    Value: !GetAtt StaticWebsite.Arn
